apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-runtime-config
data:
  ELASTIC_STORE_BACKEND: dynamodb
  ELASTIC_JOBS_TABLE_NAME: elastic-dev-jobs
  ELASTIC_INPUT_BUCKET_NAME: elastic-dev-media-111111111111-us-east-1
  ELASTIC_INGEST_QUEUE_NAME: elastic-dev-ingest
  ELASTIC_AWS_REGION: us-east-1
  ELASTIC_AUTO_CREATE_JOBS_TABLE: "false"
  ELASTIC_AUTO_CREATE_INPUT_BUCKET: "false"
  ELASTIC_AUTO_CREATE_INGEST_QUEUE: "false"
  ELASTIC_AUTO_CONFIGURE_BUCKET_NOTIFICATIONS: "false"
