apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/elastic-dev-worker
    eks.amazonaws.com/sts-regional-endpoints: "true"
